-- Demo data (fictional people and agencies)

insert into public.users
  (full_name, email, agency, business_unit, department, location, job_title, time_lock)
values
  ('Amelia Hart', 'amelia.hart@bluepeakdigital.com', 'Bluepeak Digital', 'Technology', 'Engineering', 'Chicago', 'Front-end Developer', false),
  ('Rohan Mehta', 'rohan.mehta@harborandvine.com', 'Harbor & Vine', 'Operations', 'Finance', 'Toronto', 'Billing Coordinator', false),
  ('Sofia Alvarez', 'sofia.alvarez@meridianmg.com', 'Meridian Media Group', 'Operations', 'Finance', 'New York', 'Finance Manager', false),
  ('Daniel Okafor', 'daniel.okafor@northlightcreative.com', 'Northlight Creative', 'Technology', 'Engineering', 'Dubai', 'Software Engineer', false),
  ('Priya Nair', 'priya.nair@meridianmg.com', 'Meridian Media Group', 'Client Services', 'Account Management', 'Toronto', 'Account Director', false),
  ('Liam O''Connor', 'liam.oconnor@meridianmg.com', 'Meridian Media Group', 'Media', 'Media Planning', 'London', 'Senior Media Planner', false),
  ('Hannah Schmidt', 'hannah.schmidt@harborandvine.com', 'Harbor & Vine', 'Media', 'Media Buying', 'Chicago', 'Media Buyer', false),
  ('Kenji Tanaka', 'kenji.tanaka@fieldhousestudio.com', 'Fieldhouse Studio', 'Strategy', 'Insights & Analytics', 'Sydney', 'Insights Manager', true),
  ('Chloe Dubois', 'chloe.dubois@harborandvine.com', 'Harbor & Vine', 'Creative', 'Copywriting', 'Singapore', 'Copywriter', false),
  ('Marcus Reid', 'marcus.reid@bluepeakdigital.com', 'Bluepeak Digital', 'Strategy', 'Brand Strategy', 'Chicago', 'Senior Strategist', false),
  ('Aisha Rahman', 'aisha.rahman@fieldhousestudio.com', 'Fieldhouse Studio', 'Strategy', 'Brand Strategy', 'Singapore', 'Head of Strategy', true),
  ('Ethan Brooks', 'ethan.brooks@fieldhousestudio.com', 'Fieldhouse Studio', 'Operations', 'Finance', 'Sydney', 'Finance Manager', true),
  ('Isabella Rossi', 'isabella.rossi@bluepeakdigital.com', 'Bluepeak Digital', 'Creative', 'Copywriting', 'Sydney', 'Senior Copywriter', false),
  ('Noah Fischer', 'noah.fischer@harborandvine.com', 'Harbor & Vine', 'Operations', 'People & Talent', 'Chicago', 'Talent Acquisition Partner', false),
  ('Maya Patel', 'maya.patel@meridianmg.com', 'Meridian Media Group', 'Creative', 'Design', 'Dubai', 'Design Director', false),
  ('Oliver Grant', 'oliver.grant@bluepeakdigital.com', 'Bluepeak Digital', 'Creative', 'Design', 'Berlin', 'Senior Designer', false),
  ('Zara Khan', 'zara.khan@bluepeakdigital.com', 'Bluepeak Digital', 'Technology', 'IT Operations', 'Chicago', 'Systems Administrator', false),
  ('Lucas Moreau', 'lucas.moreau@meridianmg.com', 'Meridian Media Group', 'Media', 'Media Buying', 'New York', 'Programmatic Trader', true),
  ('Grace Liu', 'grace.liu@fieldhousestudio.com', 'Fieldhouse Studio', 'Operations', 'Finance', 'London', 'Finance Manager', false),
  ('Samuel Adeyemi', 'samuel.adeyemi@bluepeakdigital.com', 'Bluepeak Digital', 'Client Services', 'Project Management', 'Berlin', 'Senior Project Manager', true),
  ('Emily Carter', 'emily.carter@meridianmg.com', 'Meridian Media Group', 'Media', 'Media Planning', 'Dubai', 'Senior Media Planner', false),
  ('Arjun Kapoor', 'arjun.kapoor@bluepeakdigital.com', 'Bluepeak Digital', 'Creative', 'Design', 'Chicago', 'Art Director', false),
  ('Freya Lindqvist', 'freya.lindqvist@bluepeakdigital.com', 'Bluepeak Digital', 'Strategy', 'Brand Strategy', 'New York', 'Strategist', true),
  ('Jacob Nguyen', 'jacob.nguyen@northlightcreative.com', 'Northlight Creative', 'Strategy', 'Brand Strategy', 'Dubai', 'Head of Strategy', false),
  ('Leila Haddad', 'leila.haddad@northlightcreative.com', 'Northlight Creative', 'Strategy', 'Insights & Analytics', 'Toronto', 'Insights Manager', true),
  ('Thomas Walsh', 'thomas.walsh@northlightcreative.com', 'Northlight Creative', 'Strategy', 'Brand Strategy', 'Dubai', 'Head of Strategy', false),
  ('Nina Kowalski', 'nina.kowalski@fieldhousestudio.com', 'Fieldhouse Studio', 'Operations', 'People & Talent', 'Dubai', 'Talent Acquisition Partner', false),
  ('Mateo Fernandez', 'mateo.fernandez@bluepeakdigital.com', 'Bluepeak Digital', 'Operations', 'People & Talent', 'Toronto', 'Talent Acquisition Partner', false),
  ('Ava Thompson', 'ava.thompson@meridianmg.com', 'Meridian Media Group', 'Creative', 'Design', 'Dubai', 'Art Director', true),
  ('Hiroshi Sato', 'hiroshi.sato@meridianmg.com', 'Meridian Media Group', 'Media', 'Media Planning', 'Sydney', 'Media Planner', true),
  ('Olivia Bennett', 'olivia.bennett@fieldhousestudio.com', 'Fieldhouse Studio', 'Technology', 'Engineering', 'Chicago', 'Software Engineer', false),
  ('Karan Singh', 'karan.singh@harborandvine.com', 'Harbor & Vine', 'Client Services', 'Project Management', 'Dubai', 'Producer', false),
  ('Elena Petrova', 'elena.petrova@harborandvine.com', 'Harbor & Vine', 'Creative', 'Design', 'Chicago', 'Art Director', false),
  ('James Mitchell', 'james.mitchell@northlightcreative.com', 'Northlight Creative', 'Strategy', 'Insights & Analytics', 'Chicago', 'Insights Manager', false),
  ('Mei Chen', 'mei.chen@meridianmg.com', 'Meridian Media Group', 'Media', 'Media Planning', 'Sydney', 'Senior Media Planner', false),
  ('Omar Farouk', 'omar.farouk@northlightcreative.com', 'Northlight Creative', 'Strategy', 'Insights & Analytics', 'Singapore', 'Insights Manager', false),
  ('Charlotte Evans', 'charlotte.evans@harborandvine.com', 'Harbor & Vine', 'Technology', 'IT Operations', 'Singapore', 'Systems Administrator', true),
  ('Diego Ramirez', 'diego.ramirez@bluepeakdigital.com', 'Bluepeak Digital', 'Client Services', 'Project Management', 'Berlin', 'Senior Project Manager', false),
  ('Sarah Cohen', 'sarah.cohen@harborandvine.com', 'Harbor & Vine', 'Creative', 'Design', 'Sydney', 'Art Director', false),
  ('Benjamin Clarke', 'benjamin.clarke@fieldhousestudio.com', 'Fieldhouse Studio', 'Creative', 'Copywriting', 'Chicago', 'Copywriter', false);
